Controllers/FieldController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebsiteManagerPanel.Commands.FieldsDeleteCommand;
using WebsiteManagerPanel.Commands.FieldsInsertCommand;
using WebsiteManagerPanel.Data.Entities.Enums;
using WebsiteManagerPanel.Framework.Infrastructure;
using WebsiteManagerPanel.Query;
using WebsiteManagerPanel.Models;
using static WebsiteManagerPanel.Framework.RoleEnums.Enum;
using WebsiteManagerPanel.Commands.FieldsUpdateCommand;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebsiteManagerPanel.Controllers
{

    public class FieldController : Controller
    {
        // GET: /<controller>/

        private readonly IMediator _mediator;
        private readonly FieldQuery _fieldQuery;
        private readonly DefinitionQuery _definitionQuery;
        private readonly FieldValueQuery _fieldValueQuery;

        public FieldController(IMediator mediator,  FieldQuery fieldQuery,DefinitionQuery definitionQuery, FieldValueQuery fieldValueQuery)
        {
            _mediator = mediator;
            _fieldQuery = fieldQuery;
            _definitionQuery = definitionQuery;
            _fieldValueQuery = fieldValueQuery;
        }
       
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.ShowField)]
        public async Task<IActionResult> Fields()
        {

             var fields = await _fieldQuery.GetAllAsync();
            return View("TableValue", fields);
        }

        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.ShowField)]
        public async Task<IActionResult> Detail(int id)
        {

            var field = await _fieldQuery.GetByIdAsync(id);
            return View("Detail", field);
        }

        [HttpGet]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Create(int definitionId)
        {
            var model = await _definitionQuery.GetFieldForInsert(definitionId);
            
            return View("Create",model);
        }
       

        // POST api/values
        [HttpPost]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Create(FieldInsertCommand value)
        {
            int result = await _mediator.Send(value);
            return RedirectToAction("Fields");
        }

        [HttpGet]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _fieldQuery.GetField(id);

            return View("Update", model);
        }


        // POST api/values
        [HttpPost]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Update(FieldUpdateCommand value)
        {
            int result = await _mediator.Send(value);
            return RedirectToAction("Detail", new { id = result });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(FieldDeleteCommand model)
        {
            await _mediator.Send(model);
            var result = new { Success = "True", Message = "Başarılı" };
            return Json(result);
        }
    }
}

Controllers/FieldItemController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WebsiteManagerPanel.Commands.DefinitionsInsertCommand;
using WebsiteManagerPanel.Commands.FieldItemsDeleteCommand;
using WebsiteManagerPanel.Commands.FieldItemsInsertCommand;
using WebsiteManagerPanel.Commands.FieldItemsUpdateCommand;
using WebsiteManagerPanel.Commands.FieldsInsertCommand;
using WebsiteManagerPanel.Commands.SitesDeleteCommand;
using WebsiteManagerPanel.Commands.SitesInsertCommand;
using WebsiteManagerPanel.Commands.SitesUpdateCommand;
using WebsiteManagerPanel.Framework.Infrastructure;
using WebsiteManagerPanel.Query;
using static WebsiteManagerPanel.Framework.RoleEnums.Enum;

namespace WebsiteManagerPanel.Controllers
{

    public class FieldItemController : Controller
    {
        // GET: /<controller>/

        private readonly IMediator _mediator;
        private readonly FieldItemQuery _fieldItemQuery;

        private readonly FieldQuery _fieldQuery;
        public FieldItemController(IMediator mediator,FieldQuery fieldQuery, FieldItemQuery fieldItemQuery)
        {
            _mediator = mediator;
            _fieldItemQuery = fieldItemQuery;
            _fieldQuery = fieldQuery;
        }


        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.ShowField)]
        public async Task<IActionResult> FieldValues()
        {

            var values = await _fieldItemQuery.GetAllAsync();
            return View("TableValue", values);
        }

        [HttpGet]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Create(int fieldId)
        {
            var model = await _fieldQuery.GetFieldValueByFieldId(fieldId);

            return View("Create",model);
        }

        [HttpPost]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Create(FieldItemInsertCommand model )
        {
            await _mediator.Send(model);
            var result = new { Success = "True", Message = "Başarılı" };
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(FieldItemDeleteCommand model)
        {
            await _mediator.Send(model);
            var result = new { Success = "True", Message = "Başarılı" };
            return Json(result);
        }
        [HttpGet]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Update(int Id)
        {
            var model = await _fieldItemQuery.GetById(Id);

            return View("Update", model);
        }

        [HttpPost]
        [ServiceFilter(typeof(PermissionFilter))]
        [RoleAttribute((int)RoleGroup.Admin, (Int64)AdminRole.CanChangeField)]
        public async Task<IActionResult> Update(FieldItemUpdateCommand model)
        {
            await _mediator.Send(model);
          return  RedirectToAction("FieldValues");
        }
    }
}

Views/FieldItem/Create.cshtml
@model FieldItemInsertViewModel
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Değer Ekleme</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


</head>
<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">Değer+</h1>

            </div>
            <h3>Yeni Değer(ler)+</h3>
            <p>Bu ekrandan <strong>@Model.SiteName</strong>sitesinin <strong>@Model.DefinitionName</strong> tanımına ait <strong>@Model.FieldName</strong> alanına dilediğiniz kadar değer ekleyebilirsiniz</p>
            <input type="hidden" id="fieldId" value="@Model.FieldId" />
            <input type="hidden" id="siteId" value="@Model.SiteId" />
            <input type="hidden" id="definitionId" value="@Model.DefinitionId" />
            <div class="col-lg 12">
                <div id="TextBoxContainer" >
                </div>
                <div class="col-lg-4">
                    <input id="btnAdd" type="button" class="fa fa plus mr-2" value="Değer eklemek için texbox ekle" onclick="AddTextBox()" />
                </div>
            </div>
            <br />
            <input type="submit" value="Kaydet" id="submit" />
            <p class="text-muted text-center"><small>Alanlara gidin ! </small></p>
            <a class="btn btn-sm btn-white btn-block" href="@Url.Action("Definition", "Definition" )">Siteler</a>
            <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; @DateTime.Now.Year</small> </p>
        </div>
    </div>
</body>
@section scripts{
    <script src="~/js/dynamic.js"></script>
    <script src="~/js/pages/fielditem/insert.js"></script>
}

Views/FieldItem/TableValue.cshtml
@{ ViewData["Title"] = "DataTables"; }
@model List<ItemViewModel>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Data Tables</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Sites", "Site")">Siteler</a>
            </li>
            <li class="breadcrumb-item">
                <a href="@Url.Action("Definitions", "Definition")">Tanımlar</a>
            </li>
            <li class="breadcrumb-item">
                <a href="@Url.Action("Fields", "Field")">Alanlar</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Veri Tablosu</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Tablodan verilere ulaşabilir filtreleme yapabilirsiniz...</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#" class="dropdown-item">Config option 1</a>
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Site</th>
                                <th>Tanım</th>
                                <th>Alan</th>
                                <th>Değer</th>
                                <th>Ekleyen</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr class="gradeX">
                                <td>@item.SiteName</td>
                                <td>
                                    @item.DefinitionName
                                </td>
                                <td>@item.FieldName</td>
                                <td class="center">@item.Value</td>
                                <td class="center">@item.CreatedName</td>
                                <td class="project-actions">
                                    <a href="/FieldItem/Update?id=@item.Id" class="btn btn-white btn-sm"><i class="fa fa-pencil mr-2"></i>Güncelle</a>
                                </td>
                            </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Site</th>
                                <th>Tanım</th>
                                <th>Alan</th>
                                <th>Değer</th>
                                <th>Ekleyen</th>
                                <th>İşlemler</th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables-example').DataTable({
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });


        });


    </script>
}

Views/FieldItem/Update.cshtml
@model FieldItemUpdateViewModel
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Değer Güncelleme</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


</head>
<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h5 class="logo-name">Değer +</h5>

            </div>
            <p><strong>@Model.SiteName</strong> sitesinin <strong>@Model.DefinitionName</strong> tanımının <strong>@Model.FieldName</strong> alanının değerini güncellemek üzeresiniz !</p>
            <form class="m-t" role="form" asp-action="Update" asp-controller="FieldItem" method="post">
                <input type="hidden" asp-for="@Model.SiteId" />
                <input type="hidden" asp-for="@Model.DefinitionId" />
                <input type="hidden" asp-for="@Model.FieldId" />
                <input type="hidden" asp-for="@Model.FieldValueId" />
                <input type="hidden" asp-for="@Model.FieldItemId" />
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Name" required="" asp-for="FieldItemValue">
                </div>
                <div class="row" id="viewCourseCodeField">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Güncelle</button>
                <p class="text-muted text-center"><small>Güncellemeyi iptal edin !</small></p>
                <a class="btn btn-sm btn-white btn-block" href="@Url.Action("Detail", "Field",new {id=Model.FieldId} )">Vazgeç</a>
                <p class="text-muted text-center"><small>Var olan alanlara gidin</small></p>
                <a class="btn btn-sm btn-white btn-block" href="@Url.Action("Fields", "Field" )">Tanımlar</a>
                <p class="text-muted text-center"><small>Tanım bilgilerine gidin !</small></p>
                <a class="btn btn-sm btn-white btn-block" href="@Url.Action("Fields", "Field" )">Tanımlara Gidin</a>
            </form>
            <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; @DateTime.Now.Year</small> </p>
        </div>
    </div>
</body>